### ISSUE TITLE
end session remotely

### ISSUE THREAD

**Issue by Milo123459** [ekzhang/sshx#36]
an ability to end the session from the web page

**Comment by ekzhang** [comment]
Thanks for your suggestion! Unfortunately I don't agree with this feature from a user interface perspective; the backend controller created the session and should be the one responsible for closing the session.

**Comment by woutervh** [comment]
@ekzhang   what is your recommendation on how to stop the session in CI, if you troubleshooted an issue as follows? 
 Currently you need to wait for a timeout?

```
name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # ... other steps ...

      - run: curl -sSf https://sshx.io/get | sh && sshx
      #      ^
      #      └ This will open a remote terminal session and print the URL. It
      #        should take under a second.
```
